uniweb/core/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from .views import home
from .views import listaAnimal, crearAnimal, actualizarAnimal
from .views import listaAvistamiento, crearAvistamiento, actualizarAvistamiento
from .views import listaGenero, crearGenero, actualizarGenero
from .views import listaEspecie, crearEspecie, actualizarEspecie
from .views import listaFinca, crearFinca, actualizarFinca
from .views import listaCamara, crearCamara, actualizarCamara
from .views import listaAvistamientom, crearAvistamientom, actualizarAvistamientom

from .views import CamaraViewSet, AvistamientoMViewSet

router = routers.DefaultRouter()
router.register(r'camaras', CamaraViewSet)
router.register(r'avistamientom', AvistamientoMViewSet)
                    
app_name = 'core'
urlpatterns = [
 	#Avistamiento
   path('avistamiento/', login_required(listaAvistamiento.as_view()), name='listaAvistamiento'),
   path('avistamiento/crear/', login_required(crearAvistamiento.as_view()), name='crearAvistamiento'),
   path('avistamiento/<pk>/act/', login_required(actualizarAvistamiento.as_view()), name='actualizarAvistamiento'),

   #Nit
   path('animal/', login_required(listaAnimal.as_view()), name='listaAnimal'),
   path('animal/crear', login_required(crearAnimal.as_view()), name='crearAnimal'),
   path('animal/<pk>/act/', login_required(actualizarAnimal.as_view()), name='actualizarAnimal'),   

   #Genero
   path('genero/', login_required(listaGenero.as_view()), name='listaGenero'),
   path('genero/crear', login_required(crearGenero.as_view()), name='crearGenero'),
   path('genero/<pk>/act/', login_required(actualizarGenero.as_view()), name='actualizarGenero'),   

   #Especie
   path('especie/', login_required(listaEspecie.as_view()), name='listaEspecie'),
   path('especie/crear', login_required(crearEspecie.as_view()), name='crearEspecie'),
   path('especie/<pk>/act/', login_required(actualizarEspecie.as_view()), name='actualizarEspecie'),   

   #Finca
   path('finca/', login_required(listaFinca.as_view()), name='listaFinca'),
   path('finca/crear', login_required(crearFinca.as_view()), name='crearFinca'),
   path('finca/<pk>/act/', login_required(actualizarFinca.as_view()), name='actualizarFinca'),   

   #Camara
   path('camara/', login_required(listaCamara.as_view()), name='listaCamara'),
   path('camara/crear', login_required(crearCamara.as_view()), name='crearCamara'),
   path('camara/<pk>/act/', login_required(actualizarCamara.as_view()), name='actualizarCamara'),   

   #AvistamientoM
   path('avistamientom/', login_required(listaAvistamientom.as_view()), name='listaAvistamientoM'),
   path('avistamientom/crear', login_required(crearAvistamientom.as_view()), name='crearAvistamientoM'),
   path('avistamientom/<pk>/act/', login_required(actualizarAvistamientom.as_view()), name='actualizarAvistamientoM'),   

   #Apis
   path('api/', include(router.urls)),
   path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

uniweb/uniweb/urls.py
from django.contrib import admin
from django.urls import path, include
from maps.views import default_map

urlpatterns = [
    path('', default_map, name='home'),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('maps/', include('maps.urls', namespace='maps')),
    path('seguridad/', include('seguridad.urls', namespace='seguridad')),
]

uniweb/templates/base/especie/formAnimal.html
<div class="content-fluid p-2">
  <h2>Crear Animal</h2>
  <hr>

  <form method="post">
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success right">Aceptar</button>
  </form>
</div>

uniweb/templates/base/especie/formEspecie.html
<div class="content-fluid p-2">
  <h2>Mantenimiento Especie</h2>
  <hr>

  <form method="post">
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success right">Aceptar</button>
  </form>
</div>

uniweb/templates/base/especie/listaAnimal.html
{% extends 'base/base.html' %}

{% block content_card %}

    <h2 class="pt-4">Animales</h2>

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-2">
            <button class="crear-colaborador btn btn-primary float-right" type="button" name="button" data-toggle="modal" data-backdrop="static" data-keyboard="false">Crear Animal</button>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Nombre Animal</th>
                    <th scope="col">Nombre Latin</th>
                    <th scope="col">Descripcion</th>
                    <th scope="col">Region</th>
                    <th scope="col">Alimentacion</th>
                </tr>
            </thead>
            <tbody>
            {% for colaborador in object_list %}
                <tr>
                    <td>{{ colaborador.nombre_animal }}</td>
                    <td>{{ colaborador.nombre_latin }}</td>
                    <td>{{ colaborador.descripcion }}</td>
                    <td>{{ colaborador.region }}</td>
                    <td>{{ colaborador.alimentacion }}</td>
                    <td>
                        <div class="dropdown">
                            <button type="button" class="update-colaborador btn btn-sm btn-primary" data-id="{% url 'core:actualizarAnimal' colaborador.id %}">
                                <span class="fa fa-edit"></span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" data-toggle="modal" data-target="#exampleModalLong">Abrir Reporte</a>
                                <a class="dropdown-item" href="#">Eliminar</a>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block add_js %}
  <script type="text/javascript">
    $(function () {
      // Create book button

      $(".crear-colaborador").modalForm({formURL: "{% url 'core:crearAnimal' %}"});

      $(".update-colaborador").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

    });
  </script>
{% endblock %}

uniweb/templates/base/especie/listaEspecie.html
{% extends 'base/base.html' %}

{% block content_card %}

    <h2 class="pt-4">Especies</h2>

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-2">
            <button class="crear-colaborador btn btn-primary float-right" type="button" name="button" data-toggle="modal" data-backdrop="static" data-keyboard="false">Crear Especie</button>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">ID Especie</th>
                    <th scope="col">Genero</th>
                    <th scope="col">Nombre Especie</th>
                    <th scope="col">Clase</th>
                    <th scope="col">Dieta</th>
                </tr>
            </thead>
            <tbody>
            {% for colaborador in object_list %}
                <tr>
                    <td>{{ colaborador.id }}</td>
                    <td>{{ colaborador.genero_fk }}</td>
                    <td>{{ colaborador.nombre_especie }}</td>
                    <td>{{ colaborador.clase }}</td>
                    <td>{{ colaborador.dieta }}</td>
                    <td>
                        <div class="dropdown">
                            <button type="button" class="update-colaborador btn btn-sm btn-primary" data-id="{% url 'core:actualizarEspecie' colaborador.id %}">
                                <span class="fa fa-edit"></span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" data-toggle="modal" data-target="#exampleModalLong">Abrir Reporte</a>
                                <a class="dropdown-item" href="#">Eliminar</a>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block add_js %}
  <script type="text/javascript">
    $(function () {
      // Create book button

      $(".crear-colaborador").modalForm({formURL: "{% url 'core:crearEspecie' %}"});

      $(".update-colaborador").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

    });
  </script>
{% endblock %}