uniweb/core/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from .views import home
from .views import listaAnimal, crearAnimal, actualizarAnimal
from .views import listaAvistamiento, crearAvistamiento, actualizarAvistamiento
from .views import listaGenero, crearGenero, actualizarGenero
from .views import listaEspecie, crearEspecie, actualizarEspecie
from .views import listaFinca, crearFinca, actualizarFinca
from .views import listaCamara, crearCamara, actualizarCamara
from .views import listaAvistamientom, crearAvistamientom, actualizarAvistamientom

from .views import CamaraViewSet, AvistamientoMViewSet

router = routers.DefaultRouter()
router.register(r'camaras', CamaraViewSet)
router.register(r'avistamientom', AvistamientoMViewSet)
                    
app_name = 'core'
urlpatterns = [
 	#Avistamiento
   path('avistamiento/', login_required(listaAvistamiento.as_view()), name='listaAvistamiento'),
   path('avistamiento/crear/', login_required(crearAvistamiento.as_view()), name='crearAvistamiento'),
   path('avistamiento/<pk>/act/', login_required(actualizarAvistamiento.as_view()), name='actualizarAvistamiento'),

   #Nit
   path('animal/', login_required(listaAnimal.as_view()), name='listaAnimal'),
   path('animal/crear', login_required(crearAnimal.as_view()), name='crearAnimal'),
   path('animal/<pk>/act/', login_required(actualizarAnimal.as_view()), name='actualizarAnimal'),   

   #Genero
   path('genero/', login_required(listaGenero.as_view()), name='listaGenero'),
   path('genero/crear', login_required(crearGenero.as_view()), name='crearGenero'),
   path('genero/<pk>/act/', login_required(actualizarGenero.as_view()), name='actualizarGenero'),   

   #Especie
   path('especie/', login_required(listaEspecie.as_view()), name='listaEspecie'),
   path('especie/crear', login_required(crearEspecie.as_view()), name='crearEspecie'),
   path('especie/<pk>/act/', login_required(actualizarEspecie.as_view()), name='actualizarEspecie'),   

   #Finca
   path('finca/', login_required(listaFinca.as_view()), name='listaFinca'),
   path('finca/crear', login_required(crearFinca.as_view()), name='crearFinca'),
   path('finca/<pk>/act/', login_required(actualizarFinca.as_view()), name='actualizarFinca'),   

   #Camara
   path('camara/', login_required(listaCamara.as_view()), name='listaCamara'),
   path('camara/crear', login_required(crearCamara.as_view()), name='crearCamara'),
   path('camara/<pk>/act/', login_required(actualizarCamara.as_view()), name='actualizarCamara'),   

   #AvistamientoM
   path('avistamientom/', login_required(listaAvistamientom.as_view()), name='listaAvistamientoM'),
   path('avistamientom/crear', login_required(crearAvistamientom.as_view()), name='crearAvistamientoM'),
   path('avistamientom/<pk>/act/', login_required(actualizarAvistamientom.as_view()), name='actualizarAvistamientoM'),   

   #Apis
   path('api/', include(router.urls)),
   path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

uniweb/seguridad/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from .views import ingresoUsuario, Usuarios, usuarioActualizar, usuario_editar
from seguridad import views as seguridad_vistas
from django.contrib.auth import views as auth_views


app_name = 'seguridad'
urlpatterns = [
    #path('ingresousuario/', ingresoUsuario.as_view(), name='ingresoUsuario'),
    path('login/', auth_views.LoginView.as_view(template_name='seguridad/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('usuarios/', Usuarios, name='mantenimiento_usuarios'),
    path('ingresousuario/', seguridad_vistas.ingresoUsuario, name='ingresoUsuario'),
    path('usuarios/<pk>/act/', login_required(usuarioActualizar.as_view()), name='usuario_actualizar'),
    #path('usuarios/<pk>/setpw/', login_required(usuarioSetPassword.as_view()), name=' usuario_setpw'),
    path('usuarios/<int:pk>/edit/<int:estado>', login_required(usuario_editar), name='usuario_editar'),
]
    

uniweb/uniweb/urls.py
from django.contrib import admin
from django.urls import path, include
from maps.views import default_map

urlpatterns = [
    path('', default_map, name='home'),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('maps/', include('maps.urls', namespace='maps')),
    path('seguridad/', include('seguridad.urls', namespace='seguridad')),
]

uniweb/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Uni - Web </title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <script src='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css' rel='stylesheet' />

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-text mx-3">UNI Web</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Admin
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Mantenimientos</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Mantenimientos:</h6>
            <a class="collapse-item" href="{% url 'core:listaGenero' %}">Genero</a>
            <a class="collapse-item" href="{% url 'core:listaEspecie' %}">Especie</a>
            <a class="collapse-item" href="{% url 'core:listaFinca' %}">Finca</a>
            <a class="collapse-item" href="{% url 'core:listaCamara' %}">Camara</a>
            <a class="collapse-item" href="{% url 'core:listaAvistamientoM' %}">Avistamiento</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item d-none">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Utilities:</h6>
            <a class="collapse-item" href="utilities-color.html">Colors</a>
            <a class="collapse-item" href="utilities-border.html">Borders</a>
            <a class="collapse-item" href="utilities-animation.html">Animations</a>
            <a class="collapse-item" href="utilities-other.html">Other</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                  {% if user.is_authenticated %}
                      {{ user.get_username }}
                  {% else %}
                      <p>Bienvenido Invitado</p>
                  {% endif %}
                </span>
                <!-- <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">-->
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
          {% block content_card %}
          {% endblock %}
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Universidad InterNaciones 2019</span>
          </div>
        </div>
      </foo ter>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cierre de Sesion</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Presione Salir para cerrar la sesion del sistema.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'seguridad:logout' %}">Salir</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %} " ></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %} " ></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %} " ></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %} " ></script>
  <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %} " ></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/chart-area-demo.js' %} " ></script>
  <script src="{% static 'js/demo/chart-pie-demo.js' %} " ></script>

    {% block add_js %}
    {% endblock %}
</body>

</html>